### ISSUE TITLE
Change toAscii to accept ascii strings

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/gurmukhi-utils#144] opened 2020-05-30 18:31 UTC
This would allow toAscii to be used to sanitize ascii strings. It would also only convert unicode gurmukhi to it's ascii counterpart for old font set ups. And it would fix any ascii character combos.

**Comment by Sarabveer** [comment] 2020-05-30 18:35
Duplicate of #145

**Comment by bhajneet** [comment] 2021-11-16 13:18
This is not a duplicate.

**Closed** 2023-07-21 14:33 UTC
Labels: ✓ Type Task
