### ISSUE TITLE
stripEndings removing number from translation

### ISSUE THREAD

**Issue by sarabveer** [ShabadOS/gurmukhi-utils#197] opened 2022-01-11 04:35 UTC
https://github.com/shabados/gurmukhi-utils/blob/2d193029dac68408fb659231ea523d683e582ac9/test/stripEndings.spec.js#L48

**Comment by Sarabveer** [comment] 2022-01-11 04:36
Similar situation here, 1753 is part of the translation

https://github.com/shabados/gurmukhi-utils/blob/2d193029dac68408fb659231ea523d683e582ac9/test/stripEndings.spec.js#L103

**Comment by bhajneet** [comment] 2022-01-11 12:37
As indicated by the comment/documentation:

Not designed for headings or Sirlekhs.

**Comment by bhajneet** [comment] 2022-01-11 13:26
I didn't see the second comment. Re-opening as an issue and renaming title.

**Comment by InderdeepBajwa** [comment] 2022-05-16 05:29
This is caused by: https://github.com/shabados/gurmukhi-utils/blob/bd76ea455f50af141593396b1f0b6c2ab24bd9d3/lib/stripEndings.js#L31

**Comment by bhajneet** [comment] 2023-07-21 14:51
This is fixed in python. The following tests pass.

```

    {
      "name": "remove line endings - negative",
      "functions": ["rle"],
      "type": "is",
      "assertions": {
        "ਮਹਲਾ ੧": "ਮਹਲਾ ੧",
        "ਮਹਲਾ ੫": "ਮਹਲਾ ੫",
        "mahalaa 1": "mahalaa 1",
        "महला ५": "महला ५",
        "It was Bikrami Samvat 1753": "It was Bikrami Samvat 1753"
      }
    }
```

**Closed by bhajneet** 2023-07-21 14:51 UTC
Labels: ○ Type Bug
